// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: aspirante.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// La solicitud para obtener un solo aspirante por ID.
type GetAspiranteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAspiranteRequest) Reset() {
	*x = GetAspiranteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspirante_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAspiranteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAspiranteRequest) ProtoMessage() {}

func (x *GetAspiranteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aspirante_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAspiranteRequest.ProtoReflect.Descriptor instead.
func (*GetAspiranteRequest) Descriptor() ([]byte, []int) {
	return file_aspirante_proto_rawDescGZIP(), []int{0}
}

func (x *GetAspiranteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// La respuesta que contiene un solo aspirante.
type AspiranteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aspirante *Aspirante `protobuf:"bytes,1,opt,name=aspirante,proto3" json:"aspirante,omitempty"`
}

func (x *AspiranteResponse) Reset() {
	*x = AspiranteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspirante_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspiranteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspiranteResponse) ProtoMessage() {}

func (x *AspiranteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aspirante_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspiranteResponse.ProtoReflect.Descriptor instead.
func (*AspiranteResponse) Descriptor() ([]byte, []int) {
	return file_aspirante_proto_rawDescGZIP(), []int{1}
}

func (x *AspiranteResponse) GetAspirante() *Aspirante {
	if x != nil {
		return x.Aspirante
	}
	return nil
}

// La solicitud para obtener aspirantes, puede incluir parámetros de filtrado.
type AspiranteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AspiranteRequest) Reset() {
	*x = AspiranteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspirante_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspiranteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspiranteRequest) ProtoMessage() {}

func (x *AspiranteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aspirante_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspiranteRequest.ProtoReflect.Descriptor instead.
func (*AspiranteRequest) Descriptor() ([]byte, []int) {
	return file_aspirante_proto_rawDescGZIP(), []int{2}
}

// La respuesta que contiene la lista de aspirantes.
type AspirantesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aspirantes []*Aspirante `protobuf:"bytes,1,rep,name=aspirantes,proto3" json:"aspirantes,omitempty"`
}

func (x *AspirantesResponse) Reset() {
	*x = AspirantesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspirante_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AspirantesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspirantesResponse) ProtoMessage() {}

func (x *AspirantesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aspirante_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspirantesResponse.ProtoReflect.Descriptor instead.
func (*AspirantesResponse) Descriptor() ([]byte, []int) {
	return file_aspirante_proto_rawDescGZIP(), []int{3}
}

func (x *AspirantesResponse) GetAspirantes() []*Aspirante {
	if x != nil {
		return x.Aspirantes
	}
	return nil
}

// Define la estructura de un aspirante.
type Aspirante struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre           string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Apellido         string `protobuf:"bytes,3,opt,name=apellido,proto3" json:"apellido,omitempty"`
	ImagenPrincipal  string `protobuf:"bytes,4,opt,name=imagen_principal,json=imagenPrincipal,proto3" json:"imagen_principal,omitempty"`
	ImagenSecundaria string `protobuf:"bytes,5,opt,name=imagen_secundaria,json=imagenSecundaria,proto3" json:"imagen_secundaria,omitempty"`
	Carrera          string `protobuf:"bytes,6,opt,name=carrera,proto3" json:"carrera,omitempty"`
	// El campo lenguajes_programacion puede ser una lista de strings
	LenguajesProgramacion []string `protobuf:"bytes,7,rep,name=lenguajes_programacion,json=lenguajesProgramacion,proto3" json:"lenguajes_programacion,omitempty"`
}

func (x *Aspirante) Reset() {
	*x = Aspirante{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspirante_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aspirante) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aspirante) ProtoMessage() {}

func (x *Aspirante) ProtoReflect() protoreflect.Message {
	mi := &file_aspirante_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aspirante.ProtoReflect.Descriptor instead.
func (*Aspirante) Descriptor() ([]byte, []int) {
	return file_aspirante_proto_rawDescGZIP(), []int{4}
}

func (x *Aspirante) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Aspirante) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Aspirante) GetApellido() string {
	if x != nil {
		return x.Apellido
	}
	return ""
}

func (x *Aspirante) GetImagenPrincipal() string {
	if x != nil {
		return x.ImagenPrincipal
	}
	return ""
}

func (x *Aspirante) GetImagenSecundaria() string {
	if x != nil {
		return x.ImagenSecundaria
	}
	return ""
}

func (x *Aspirante) GetCarrera() string {
	if x != nil {
		return x.Carrera
	}
	return ""
}

func (x *Aspirante) GetLenguajesProgramacion() []string {
	if x != nil {
		return x.LenguajesProgramacion
	}
	return nil
}

var File_aspirante_proto protoreflect.FileDescriptor

var file_aspirante_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x11, 0x41, 0x73, 0x70, 0x69,
	0x72, 0x61, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x09, 0x61, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x41, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x52, 0x09, 0x61, 0x73,
	0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x73, 0x70, 0x69, 0x72,
	0x61, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x12, 0x41,
	0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x0a, 0x61, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74,
	0x65, 0x52, 0x0a, 0x61, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x22, 0xf8, 0x01,
	0x0a, 0x09, 0x41, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x70, 0x65, 0x6c, 0x6c, 0x69, 0x64, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x70, 0x65, 0x6c, 0x6c, 0x69, 0x64, 0x6f, 0x12,
	0x29, 0x0a, 0x10, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69,
	0x70, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x6e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x12, 0x2b, 0x0a, 0x11, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x69, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x53, 0x65, 0x63,
	0x75, 0x6e, 0x64, 0x61, 0x72, 0x69, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x72, 0x65,
	0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x72, 0x65, 0x72,
	0x61, 0x12, 0x35, 0x0a, 0x16, 0x6c, 0x65, 0x6e, 0x67, 0x75, 0x61, 0x6a, 0x65, 0x73, 0x5f, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x15, 0x6c, 0x65, 0x6e, 0x67, 0x75, 0x61, 0x6a, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x32, 0x89, 0x01, 0x0a, 0x10, 0x41, 0x73, 0x70,
	0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x41, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x12, 0x14, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x41, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x41, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x41, 0x73, 0x70,
	0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x41, 0x73, 0x70, 0x69, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x63, 0x61, 0x73, 0x6f, 0x2f, 0x70, 0x72, 0x75, 0x65, 0x62, 0x61,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aspirante_proto_rawDescOnce sync.Once
	file_aspirante_proto_rawDescData = file_aspirante_proto_rawDesc
)

func file_aspirante_proto_rawDescGZIP() []byte {
	file_aspirante_proto_rawDescOnce.Do(func() {
		file_aspirante_proto_rawDescData = protoimpl.X.CompressGZIP(file_aspirante_proto_rawDescData)
	})
	return file_aspirante_proto_rawDescData
}

var file_aspirante_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_aspirante_proto_goTypes = []interface{}{
	(*GetAspiranteRequest)(nil), // 0: GetAspiranteRequest
	(*AspiranteResponse)(nil),   // 1: AspiranteResponse
	(*AspiranteRequest)(nil),    // 2: AspiranteRequest
	(*AspirantesResponse)(nil),  // 3: AspirantesResponse
	(*Aspirante)(nil),           // 4: Aspirante
}
var file_aspirante_proto_depIdxs = []int32{
	4, // 0: AspiranteResponse.aspirante:type_name -> Aspirante
	4, // 1: AspirantesResponse.aspirantes:type_name -> Aspirante
	0, // 2: AspiranteService.GetAspirante:input_type -> GetAspiranteRequest
	2, // 3: AspiranteService.GetAspirantes:input_type -> AspiranteRequest
	1, // 4: AspiranteService.GetAspirante:output_type -> AspiranteResponse
	3, // 5: AspiranteService.GetAspirantes:output_type -> AspirantesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aspirante_proto_init() }
func file_aspirante_proto_init() {
	if File_aspirante_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aspirante_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAspiranteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspirante_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspiranteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspirante_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspiranteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspirante_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AspirantesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspirante_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aspirante); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aspirante_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aspirante_proto_goTypes,
		DependencyIndexes: file_aspirante_proto_depIdxs,
		MessageInfos:      file_aspirante_proto_msgTypes,
	}.Build()
	File_aspirante_proto = out.File
	file_aspirante_proto_rawDesc = nil
	file_aspirante_proto_goTypes = nil
	file_aspirante_proto_depIdxs = nil
}
